################################################################################
# Automatically-generated file. Do not edit!
################################################################################

CPP_SRCS := 
C_UPPER_SRCS := 
C_SRCS := 
S_UPPER_SRCS := 
ASM_SRCS := 
CXX_SRCS := 
C++_SRCS := 
CC_SRCS := 
C++_DEPS := 
OBJS := 
C_DEPS := 
ASM_DEPS := 
CC_DEPS := 
CPP_DEPS := 
CXX_DEPS := 
C_UPPER_DEPS := 
S_UPPER_DEPS := 

# Every subdirectory with source files must be described here
SUBDIRS := \
targets/hal/TARGET_STM/TARGET_STM32F4XX \
targets/hal/TARGET_NXP/TARGET_LPC81X/TARGET_LPC81X_COMMON \
targets/hal/TARGET_NXP/TARGET_LPC43XX \
targets/hal/TARGET_NXP/TARGET_LPC408X \
targets/hal/TARGET_NXP/TARGET_LPC23XX \
targets/hal/TARGET_NXP/TARGET_LPC176X \
targets/hal/TARGET_NXP/TARGET_LPC13XX \
targets/hal/TARGET_NXP/TARGET_LPC11XX_11CXX \
targets/hal/TARGET_NXP/TARGET_LPC11XX_11CXX/TARGET_LPC11CXX \
targets/hal/TARGET_NXP/TARGET_LPC11UXX \
targets/hal/TARGET_Freescale/TARGET_KL46Z \
targets/hal/TARGET_Freescale/TARGET_KL25Z \
targets/hal/TARGET_Freescale/TARGET_KL05Z \
targets/cmsis/TARGET_STM/TARGET_STM32F4XX \
targets/cmsis/TARGET_STM/TARGET_STM32F4XX/TOOLCHAIN_ARM_STD \
targets/cmsis/TARGET_NXP/TARGET_LPC81X/TARGET_LPC81X_COMMON \
targets/cmsis/TARGET_NXP/TARGET_LPC81X/TARGET_LPC81X_COMMON/TOOLCHAIN_ARM_MICRO \
targets/cmsis/TARGET_NXP/TARGET_LPC81X/TARGET_LPC812 \
targets/cmsis/TARGET_NXP/TARGET_LPC81X/TARGET_LPC810 \
targets/cmsis/TARGET_NXP/TARGET_LPC43XX \
targets/cmsis/TARGET_NXP/TARGET_LPC43XX/TOOLCHAIN_GCC_CR \
targets/cmsis/TARGET_NXP/TARGET_LPC43XX/TOOLCHAIN_ARM_STD \
targets/cmsis/TARGET_NXP/TARGET_LPC408X \
targets/cmsis/TARGET_NXP/TARGET_LPC408X/TOOLCHAIN_GCC_CR \
targets/cmsis/TARGET_NXP/TARGET_LPC408X/TOOLCHAIN_ARM_STD \
targets/cmsis/TARGET_NXP/TARGET_LPC23XX \
targets/cmsis/TARGET_NXP/TARGET_LPC23XX/TOOLCHAIN_ARM_STD \
targets/cmsis/TARGET_NXP/TARGET_LPC23XX/TOOLCHAIN_ARM_MICRO \
targets/cmsis/TARGET_NXP/TARGET_LPC176X \
targets/cmsis/TARGET_NXP/TARGET_LPC176X/TOOLCHAIN_GCC_CS \
targets/cmsis/TARGET_NXP/TARGET_LPC176X/TOOLCHAIN_GCC_CR \
targets/cmsis/TARGET_NXP/TARGET_LPC176X/TOOLCHAIN_ARM_STD \
targets/cmsis/TARGET_NXP/TARGET_LPC176X/TOOLCHAIN_ARM_MICRO \
targets/cmsis/TARGET_NXP/TARGET_LPC13XX \
targets/cmsis/TARGET_NXP/TARGET_LPC13XX/TOOLCHAIN_ARM_STD \
targets/cmsis/TARGET_NXP/TARGET_LPC13XX/TOOLCHAIN_ARM_MICRO \
targets/cmsis/TARGET_NXP/TARGET_LPC11XX_11CXX \
targets/cmsis/TARGET_NXP/TARGET_LPC11XX_11CXX/TOOLCHAIN_GCC_CS \
targets/cmsis/TARGET_NXP/TARGET_LPC11XX_11CXX/TOOLCHAIN_GCC_CR \
targets/cmsis/TARGET_NXP/TARGET_LPC11XX_11CXX/TOOLCHAIN_ARM_STD \
targets/cmsis/TARGET_NXP/TARGET_LPC11XX_11CXX/TOOLCHAIN_ARM_MICRO \
targets/cmsis/TARGET_NXP/TARGET_LPC11XX_11CXX/TARGET_LPC11XX \
targets/cmsis/TARGET_NXP/TARGET_LPC11XX_11CXX/TARGET_LPC11CXX \
targets/cmsis/TARGET_NXP/TARGET_LPC11UXX \
targets/cmsis/TARGET_NXP/TARGET_LPC11UXX/TOOLCHAIN_GCC_CS \
targets/cmsis/TARGET_NXP/TARGET_LPC11UXX/TOOLCHAIN_GCC_CR \
targets/cmsis/TARGET_NXP/TARGET_LPC11UXX/TOOLCHAIN_ARM_STD \
targets/cmsis/TARGET_NXP/TARGET_LPC11UXX/TOOLCHAIN_ARM_MICRO \
targets/cmsis/TARGET_Freescale/TARGET_KL46Z \
targets/cmsis/TARGET_Freescale/TARGET_KL46Z/TOOLCHAIN_ARM_STD \
targets/cmsis/TARGET_Freescale/TARGET_KL25Z \
targets/cmsis/TARGET_Freescale/TARGET_KL25Z/TOOLCHAIN_GCC_CW_EWL \
targets/cmsis/TARGET_Freescale/TARGET_KL25Z/TOOLCHAIN_ARM_STD \
targets/cmsis/TARGET_Freescale/TARGET_KL25Z/TOOLCHAIN_ARM_MICRO \
targets/cmsis/TARGET_Freescale/TARGET_KL05Z \
targets/cmsis/TARGET_Freescale/TARGET_KL05Z/TOOLCHAIN_ARM_STD \
common \

